# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: swift

env:
 global:
  - WORKSPACE='Example/TableviewPaginator.xcworkspace'
  - EXAMPLE_SCHEME='TableviewPaginator-Example'
  - IOS_DESTINATION='platform=iOS Simulator,name=iPhone 6 Plus,OS=12.1'

# cache: cocoapods
podfile: Example/Podfile
xcode_sdk: iphonesimulator11.4
before_install:
 - gem install cocoapods # Since Travis is not always on latest version
 - pod repo update
 - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace "$WORKSPACE"  -scheme "$EXAMPLE_SCHEME" -destination "$IOS_DESTINATION" ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --allow-warnings

#set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace "Example/TableviewPaginator.xcworkspace"  -scheme "TableviewPaginator-Example" -destination "platform=iOS Simulator,name=iPhone 6 Plus,OS=12.1" ONLY_ACTIVE_ARCH=NO | xcpretty
